fragment PostParts on Post {
  __typename
  title
  layout
  episode
  file
  time
  cover
  description
  body
}

fragment AudiobookParts on Audiobook {
  __typename
  title
  layout
  series
  chapter
  author
  series_slug
  cover
  audio_file
  time
  body
}
